# 常用的公司財報指標

In [28]:
import pandas as pd
from finlab.data import Data
data = Data()
df = pd.read_pickle("history/tables/benchmark.pkl")
# 現金及約當現金 
for name in data.col2table.keys():
    if '約當現金' in name:
        print(name)

現金及約當現金合計
現金及約當現金總額
現金及約當現金
約當現金
資產負債表帳列之現金及約當現金
分類至待分配與業主之（非流動）資產（或處分群組）之現金及約當現金
本期現金及約當現金增加（減少）數
期初現金及約當現金餘額
符合國際會計準則第七號現金及約當現金定義之存放央行及拆借銀行同業
分類至待出售（非流動）資產（或處分群組）之現金及約當現金
匯率變動對現金及約當現金之影響
分類至待分配與業主之（非流動）資產（或處分群組）之現金及約當現金-
分類至待出售（非流動）資產（或處分群組）之現金及約當現金-
符合國際會計準則第七號現金及約當現金定義之附賣回票券及債券投資
其他符合國際會計準則第七號現金及約當現金定義之項目
期末現金及約當現金餘額

# 不同欄位但是同一名稱

In [31]:
for name in data.col2table.keys():
    if "約當現金" in name:
        print(name)

data.get("現金及約當現金合計").fillna(data.get("現金及約當現金總額")).fillna(data.get("現金及約當現金"))

現金及約當現金合計
現金及約當現金總額
現金及約當現金
約當現金
資產負債表帳列之現金及約當現金
分類至待分配與業主之（非流動）資產（或處分群組）之現金及約當現金
本期現金及約當現金增加（減少）數
期初現金及約當現金餘額
符合國際會計準則第七號現金及約當現金定義之存放央行及拆借銀行同業
分類至待出售（非流動）資產（或處分群組）之現金及約當現金
匯率變動對現金及約當現金之影響
分類至待分配與業主之（非流動）資產（或處分群組）之現金及約當現金-
分類至待出售（非流動）資產（或處分群組）之現金及約當現金-
符合國際會計準則第七號現金及約當現金定義之附賣回票券及債券投資
其他符合國際會計準則第七號現金及約當現金定義之項目
期末現金及約當現金餘額

stock_id,000116,000538,000616,000700,000779,000815,000888,000930,000960,000980,...,9964,9968,9971,9977,9978,9982,9983,9984,9985,9986
date,,,,,,,,,,,,,,,,,,,,,
2013-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-08-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-08-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-08-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-08-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-08-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-08-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-05-15,4425058.0,2368166.0,1754938.0,1123475.0,1151186.0,1414387.0,3071556.0,2906292.0,13234743.0,44309393.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-08-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,116233.0,385336.0,2495216.0,31163.0,1000318.0,46562.0,51099.0,62004.0,221546.0,35923.0
2019-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 計算所有財經指數

In [22]:
import pandas as pd

T0112現金及約當現金 = data.get("期末現金及約當現金餘額")
T3900繼續營業部門稅前純益 = data.get('繼續營業單位稅前淨利（淨損）')
T3970經常稅後淨利 = data.get('本期淨利（淨損）').fillna(data.get('本期稅後淨利（淨損）'))
T2000權益總計 = data.get('權益總計').fillna(data.get('權益總額'))
T3295營業毛利 = data.get('營業毛利（毛損）').fillna(data.get('營業毛利（毛損）淨額'))
T3100營業收入淨額 = data.get("營業收入合計")
T3700營業外收入及支出 = data.get("營業外收入及支出合計").fillna(data.get("營業外損益合計"))
T3910所得稅費用 = (data.get("所得稅費用（利益）合計").fillna(data.get("本期所得稅費用（利益）"))
    .fillna(data.get("當期所得稅費用（利益）"))
    .fillna(data.get("所得稅費用（利益）淨額"))
    .fillna(data.get("所得稅費用（利益）"))
    .fillna(-data.get("所得稅（費用）利益").fillna(data.get("所得稅利益（費用）")).dropna(how='all', axis=1))
)
T3300營業費用 = data.get("營業費用合計")
T7211折舊 = data.get('折舊費用', table='cash_flows')
T7212攤提 = data.get('攤銷費用', table='cash_flows')

T3920繼續營業部門純益 = T3900繼續營業部門稅前純益 - T3910所得稅費用
T0170存貨 = data.get("存貨合計").fillna(data.get("存貨"))
股本 = data.get('股本合計')
T0400不動產廠房設備合計 = (data.get("不動產、廠房及設備合計")
                  .fillna(data.get("不動產、廠房及設備"))
                  .fillna(data.get("不動產及設備合計"))
                  .fillna(data.get('不動產、廠房及設備淨額'))
                  .fillna(data.get("不動產及設備－淨額"))
                 )
T0960非流動資產 = data.get("非流動資產合計").fillna(data.get("非流動資產淨額"))
T1800非流動負債 = data.get("非流動負債合計")
T1100流動負債 = data.get("流動負債合計").fillna(data.get("流動負債總額"))
T0100流動資產 = data.get("流動資產合計")
T3501財物成本 = data.get('財務成本').fillna(data.get("財務成本淨額"))
T0010資產總額 = T0100流動資產 + T0960非流動資產
T3971本期綜合損益總額 = data.get("本期綜合損益總額").fillna(data.get("綜合損益總額"))
T3395營業利益 = data.get('營業利益（損失）').fillna(data.get('營業利益'))
T2403稅前息前折舊前淨利 = T3900繼續營業部門稅前純益 + T3501財物成本 + T7211折舊 + T7212攤提
T2402稅前息前淨利 = T3900繼續營業部門稅前純益 + T3501財物成本
R202用人費用率 = data.get("管理費用合計").fillna(data.get("管理費用"))
T3356研究發展費 = data.get("研究發展費用").fillna(data.get("研究發展費用合計")).fillna(data.get("委託研究費"))
T7210營運現金流 = data.get("營運產生之現金流入（流出）")
T3950歸屬母公司淨利 = data.get("歸屬於母公司業主之權益合計")
T1000負債總額 = data.get("負債總額").fillna(data.get("負債總計"))
T3200營業成本 = data.get("營業成本合計")
T7324取得不動產廠房及設備 = (data.get("取得不動產、廠房及設備")
                  .fillna(data.get("取得不動產及設備")))
#2018年(含)以後所得稅率為20% 
#2010年(含)至2017年(含)期間所得稅率為17% 
#2009年(含)以前所得稅率為25% 

所得稅率 = pd.DataFrame(0.2, index=T3501財物成本.index, columns=T3501財物成本.columns)
所得稅率.loc[:'2017'] = 17
所得稅率.loc[:'2009'] = 25

# 獲利能力指標
R101_ROA稅後息前 = (T3920繼續營業部門純益 + T3501財物成本 * (1 - 所得稅率)) / (T0010資產總額 + T0010資產總額.shift()) * 2 * 100
R11V_ROA綜合損益 = T3971本期綜合損益總額 / (T0010資產總額 + T0010資產總額.shift()) * 2 * 100
R103_ROE稅後 =  T3920繼續營業部門純益 /(T2000權益總計 + T2000權益總計.shift()).abs() * 2 * 100
R11U_ROE綜合損益 =  (T3971本期綜合損益總額/((T2000權益總計+T2000權益總計.shift())/2)) * 100

R145_稅前息前折舊前淨利率 = T2403稅前息前折舊前淨利/T3100營業收入淨額*100
R105_營業毛利率 = T3295營業毛利 / T3100營業收入淨額 *100
R106_營業利益率 = T3395營業利益 / T3100營業收入淨額 *100
R107_稅前淨利率 = T3900繼續營業部門稅前純益 / T3100營業收入淨額 *100
R108_稅後淨利率 = T3970經常稅後淨利 / T3100營業收入淨額 *100
R112_業外收支營收率 = T3700營業外收入及支出 / T3100營業收入淨額 * 100
R179_貝里比率 = T3295營業毛利 / T3300營業費用 * 100

# 成本費用率指標
R203_研究發展費用率 = T3356研究發展費 / T3300營業費用 * 100
R205_現金流量比率 = T7210營運現金流 / T1100流動負債 *100
R207_稅率 = (T3910所得稅費用 / T3900繼續營業部門稅前純益 *100)
R207_稅率[(T3900繼續營業部門稅前純益 <= 0) | (T3910所得稅費用 <= 0)] = 0

# 償債能力指標
R304_每股營業額 = T3100營業收入淨額/股本 * 10
R305_每股營業利益 = T3395營業利益 / 股本 * 10
R303_每股現金流量 = T7210營運現金流 / 股本 * 10
R306_每股稅前淨利 = T3900繼續營業部門稅前純益 / 股本 * 10
R314_每股綜合損益 = T3971本期綜合損益總額 / 股本 * 10
R315_每股稅前淨利 = T3900繼續營業部門稅前純益 / 股本 * 10
R316_每股稅後淨利 = T3950歸屬母公司淨利 / 股本 * 10
R504_總負債除總淨值 = T1000負債總額 / T2000權益總計 * 100
R505_負債比率 = T1000負債總額 / T0010資產總額 * 100
R506_淨值除資產 = T2000權益總計 / T0010資產總額 * 100


# 成長率指標
def 成長率(s):
    return (s / s.shift(4) - 1) * 100

R401_營收成長率 = 成長率(T3100營業收入淨額)
R402_營業毛利成長率 = 成長率(T3295營業毛利)
R403_營業利益成長率 = 成長率(T3395營業利益)
R404_稅前淨利成長率 = 成長率(T3900繼續營業部門稅前純益)
R405_稅後淨利成長率 = 成長率(T3970經常稅後淨利)
R406_經常利益成長率 = 成長率(T3920繼續營業部門純益)
R408_資產總額成長率 = 成長率(T0010資產總額)
R409_淨值成長率  = 成長率(T2000權益總計)

# 償債能力指標
R501_流動比率 = T0100流動資產 / T1100流動負債 *100
R502_速動比率 = (T0100流動資產 - T0170存貨) / T1100流動負債 *100
R503_利息支出率 = T3501財物成本 /(T3920繼續營業部門純益 + T3501財物成本 *(1-所得稅率)) *100


R678_營運資金 = T0100流動資產 - T1100流動負債
R607_總資產週轉次數 = T3100營業收入淨額 / T0010資產總額.rolling(4).sum()
R610_存貨週轉率 = T3200營業成本 / T0170存貨.rolling(4).sum()
R612_固定資產週轉次數 = T3100營業收入淨額 - T0400不動產廠房設備合計
R613_淨值週轉率次 = T3100營業收入淨額 / T2000權益總計.rolling(4).sum()
R69B_自由現金流量 = T3970經常稅後淨利 + T7211折舊 + T7212攤提 + T7324取得不動產廠房及設備 +((
    T0100流動資產 - T1100流動負債) - (T0100流動資產.shift() - T1100流動負債.shift()))

## 將這些資料整理成DataFrame

In [26]:
fundamental_data = {
        
        # 獲利能力指標
        'R101_ROA稅後息前': R101_ROA稅後息前,
        'R11V_ROA綜合損益': R11V_ROA綜合損益,
        'R103_ROE稅後': R103_ROE稅後,
        'R11U_ROE綜合損益': R11U_ROE綜合損益,
        'R145_稅前息前折舊前淨利率': R145_稅前息前折舊前淨利率,
        'R105_營業毛利率': R105_營業毛利率,
        'R106_營業利益率': R106_營業利益率,
        'R107_稅前淨利率': R107_稅前淨利率,
        'R108_稅後淨利率': R108_稅後淨利率,
        'R112_業外收支營收率': R112_業外收支營收率,
        'R179_貝里比率': R179_貝里比率,
        
        # 成本費用率指標
        'R203_研究發展費用率': R203_研究發展費用率,
        'R205_現金流量比率': R205_現金流量比率,
        'R207_稅率': R207_稅率,
        
        # 償債能力指標
        'R304_每股營業額': R304_每股營業額,
        'R305_每股營業利益': R305_每股營業利益,
        'R303_每股現金流量': R303_每股現金流量,
        'R306_每股稅前淨利': R306_每股稅前淨利,
        'R314_每股綜合損益': R314_每股綜合損益,
        'R315_每股稅前淨利': R315_每股稅前淨利,
        'R316_每股稅後淨利': R316_每股稅後淨利,
        'R504_總負債除總淨值': R504_總負債除總淨值,
        'R505_負債比率': R505_負債比率,
        'R506_淨值除資產': R506_淨值除資產,
        
        # 成長率指標
        'R401_營收成長率': R401_營收成長率,
        'R402_營業毛利成長率': R402_營業毛利成長率,
        'R403_營業利益成長率': R403_營業利益成長率,
        'R404_稅前淨利成長率': R404_稅前淨利成長率,
        'R405_稅後淨利成長率': R405_稅後淨利成長率,
        'R406_經常利益成長率': R406_經常利益成長率,
        'R408_資產總額成長率': R408_資產總額成長率,
        'R409_淨值成長率': R409_淨值成長率,
        
        # 償債能力指標
        'R501_流動比率': R501_流動比率,
        'R502_速動比率': R502_速動比率,
        'R503_利息支出率': R503_利息支出率,
        'R678_營運資金': R678_營運資金,
        'R607_總資產週轉次數': R607_總資產週轉次數,
        'R610_存貨週轉率': R610_存貨週轉率,
        'R612_固定資產週轉次數': R612_固定資產週轉次數,
        'R613_淨值週轉率次': R613_淨值週轉率次,
        'R69B_自由現金流量': R69B_自由現金流量,
}

df = pd.DataFrame({name: df.unstack() for name, df in fundamental_data.items()})

combined_data = {}
for name, df in fundamental_data.items():
    combined_data[name] = df.unstack()
    
df = pd.DataFrame(combined_data)

from finlab.ml import fundamental_features

df = fundamental_features()

In [4]:
df.loc['1101']
#['103_ROE_稅後']

,R101_ROA稅後息前,R11V_ROA綜合損益,R103_ROE稅後,R11U_ROE綜合損益,R145_稅前息前折舊前淨利率,R105_營業毛利率,R106_營業利益率,R107_稅前淨利率,R108_稅後淨利率,R112_業外收支營收率,...,R409_淨值成長率,R501_流動比率,R502_速動比率,R503_利息支出率,R678_營運資金,R607_總資產週轉次數,R610_存貨週轉率,R612_固定資產週轉次數,R613_淨值週轉率次,R69B_自由現金流量
date,,,,,,,,,,,,,,,,,,,,,
2013-05-15,NaN,NaN,NaN,NaN,18.784632,12.954574,8.404765,9.707159,8.292362,1.302394,...,NaN,117.194382,101.798106,-8.186859,11333336.0,NaN,NaN,-86927985.0,NaN,NaN
2013-08-14,3.802102e+06,0.944284,2.672149,1.813357,29.080609,19.609253,16.006148,16.075146,13.261530,0.068999,...,NaN,111.842825,97.233833,-13.298556,8168144.0,NaN,NaN,-82069133.0,NaN,2672265.0
2013-11-14,5.344659e+06,2.481737,3.758506,4.761293,39.883772,23.431517,19.632197,21.650964,17.752319,2.018767,...,NaN,104.717879,91.613871,-17.083477,3478652.0,NaN,NaN,-79745028.0,NaN,3901805.0
2014-03-31,3.972290e+06,3.102975,2.658697,5.759881,37.996392,21.147474,15.808358,15.467631,11.961897,-0.340726,...,NaN,124.701609,111.510664,-32.624816,17389561.0,0.030157,0.668462,-76161794.0,0.056922,22252358.0
2014-05-15,2.791232e+06,1.630076,1.789978,2.971092,21.368815,18.206665,13.790211,13.290971,10.447714,-0.499240,...,8.866880,123.837828,109.510229,-9.792979,17732671.0,0.023981,0.550675,-81394854.0,0.044805,3869612.0
2014-08-14,4.828692e+06,0.152556,3.158575,0.282596,31.661411,22.404973,18.630915,19.722356,15.149579,1.091441,...,5.954576,109.819505,97.360139,-17.435186,7972516.0,0.028432,0.622629,-74379365.0,0.052721,-3002140.0
2014-11-14,4.934483e+06,2.168353,3.279737,4.058708,38.475326,22.175860,18.422237,20.257292,16.396389,1.835055,...,5.657634,113.370853,100.450140,-17.800651,10552354.0,0.026593,0.581786,-76877637.0,0.049112,10205052.0
2015-03-31,4.029457e+06,3.002608,2.554910,5.476992,41.906122,20.894608,15.825841,17.763315,13.594134,1.937474,...,5.467505,140.759054,125.502509,-13.169666,27973772.0,0.025961,0.565798,-78804395.0,0.047718,24426590.0
2015-05-15,9.745154e+05,0.069454,0.601114,0.124782,17.520262,13.344165,7.898772,6.855678,4.545296,-1.043095,...,2.505042,132.899231,118.561600,-7.153186,22891238.0,0.018713,0.455819,-89211708.0,0.034296,-3122357.0
2015-08-14,2.727843e+06,0.199590,1.742001,0.375786,28.987422,15.673298,11.673239,12.973054,10.913919,1.299814,...,2.352256,121.141500,108.729163,-10.550798,16684543.0,0.021454,0.521190,-91109547.0,0.039761,-872152.0
2015-11-14,9.894244e+05,0.234421,0.641225,0.453207,31.625692,14.573879,8.801266,5.163606,4.361788,-3.637661,...,2.756219,128.276271,115.213271,-7.168014,20018498.0,0.019237,0.490699,-93900309.0,0.035845,8305359.0
2016-03-31,2.233833e+06,-0.706146,1.426808,-1.330131,43.531776,18.092512,12.483658,11.328340,9.095137,-1.155318,...,-4.032541,133.061512,119.928985,-8.738568,22509544.0,0.020823,0.529942,-88749360.0,0.039215,9417064.0
2016-05-15,9.452418e+04,-0.256684,0.060939,-0.473180,14.742183,8.946056,2.730117,1.567622,0.533324,-1.162495,...,-4.604373,121.079162,107.988508,-6.324010,13663267.0,0.015168,0.442514,-93212789.0,0.028641,-8420603.0
2016-08-14,2.708929e+06,-0.279080,1.796833,-0.506848,32.856023,22.061074,16.435528,15.117147,11.807666,-1.318381,...,-2.777525,123.713805,109.587830,-9.815913,13957345.0,0.020170,0.511048,-85056372.0,0.037326,4648606.0
2016-11-14,3.283218e+06,0.530034,2.247007,0.968280,43.904818,22.188990,16.915116,18.009221,14.690001,1.094105,...,-7.727431,119.674026,106.409533,-11.104516,12194654.0,0.020213,0.512061,-81795654.0,0.037098,4731434.0
2017-03-31,2.755392e+06,0.728356,1.881750,1.323298,42.230419,24.012585,18.830223,14.103589,10.378914,-4.726633,...,-5.201543,141.337676,125.197620,-9.786431,22779093.0,0.024589,0.594812,-75251758.0,0.044665,17334467.0
2017-05-15,1.163705e+06,0.057603,0.789102,0.102833,17.923787,14.158463,9.167380,7.909783,5.494431,-1.257596,...,-4.653916,137.378509,121.953481,-7.329636,20852624.0,0.019974,0.534183,-76059553.0,0.036071,729530.0
2017-08-14,3.070780e+06,2.052392,2.096715,3.655440,31.310565,21.315906,16.430682,16.504988,12.425237,0.074306,...,-0.958857,124.269185,109.607396,-10.905761,15493362.0,0.023453,0.554317,-72046560.0,0.042191,287815.0
2017-11-14,2.687047e+06,2.864431,1.801383,5.104247,38.083585,18.462987,14.076732,15.058493,11.653309,0.981761,...,5.162088,130.722863,116.176907,-9.640686,20052199.0,0.021791,0.517177,-73623610.0,0.038866,11123640.0
2018-03-31,3.401259e+06,2.649551,2.225854,4.699055,39.388593,21.760842,16.058472,15.661291,11.584801,-0.397181,...,3.562187,142.223814,129.408746,13.211506,27526954.0,0.027601,0.641396,-65349736.0,0.049053,15816779.0
2018-05-15,2.865370e+06,3.015032,1.799804,5.261438,28.078837,23.948835,19.234252,19.097345,11.850551,-0.136907,...,12.344125,141.051215,123.791292,16.342285,21903894.0,0.022239,0.504933,-71064622.0,0.039205,-2240345.0
2018-08-14,7.710935e+06,2.881048,4.645435,5.146213,41.175666,30.817521,26.946812,29.478718,23.141345,2.531905,...,14.344362,153.387378,139.817292,7.512533,35114382.0,0.029358,0.640640,-60383459.0,0.052261,22660566.0
2018-11-14,6.458651e+06,0.833908,3.671060,1.465268,43.302349,26.759925,22.846059,25.920229,20.084676,3.074169,...,21.367254,163.695399,149.344427,9.612559,40000340.0,0.027393,0.663401,-59146792.0,0.047976,13671786.0
2019-03-31,5.609115e+06,0.064637,2.928806,0.110103,42.700736,25.551426,20.621607,22.237081,16.054828,1.615474,...,29.304327,171.122662,156.450199,10.346478,45876851.0,0.028052,0.710440,-56156577.0,0.048863,13684428.0
2019-05-15,4.229970e+06,3.616097,2.075878,6.296433,31.129129,25.586765,19.848939,22.099000,16.682108,2.250062,...,26.781847,156.961804,143.851229,11.502824,43783949.0,0.019095,0.503433,-66460168.0,0.033390,2407225.0